'use client';
import Link from 'next/link';
import { useMemo,useRef,useState,type FormEvent } from 'react';
import { ArrowRight,FileXls,LockSimple,MagnifyingGlass,UploadSimple,WarningCircle } from '@phosphor-icons/react';
import type { ApiResponse } from '../../../src/application/apiResponse';
import type { WorkOrderBatchPreview } from '../../../src/application/workOrderBatchPreview';
import type { LedgerAction } from '../../../src/config/controlledValues';
import { ControlledActionPanel } from '../controlled-action-panel';

export function WorkOrderPreviewClient({initialBusinessDate}:{initialBusinessDate:string}){
 const [businessDate,setBusinessDate]=useState(initialBusinessDate),[action,setAction]=useState<LedgerAction>('备货');
 const [file,setFile]=useState<File>(),[preview,setPreview]=useState<WorkOrderBatchPreview>(),[systemError,setSystemError]=useState<string>(),[loading,setLoading]=useState(false),[selected,setSelected]=useState(0); const fileInput=useRef<HTMLInputElement>(null);
 async function submit(event:FormEvent){event.preventDefault();if(!file)return;setLoading(true);setSystemError(undefined);setPreview(undefined);try{const form=new FormData();form.set('businessDate',businessDate);form.set('file',file);const response=await fetch('/api/warehouse/work-orders/preview',{method:'POST',body:form});const payload=await response.json() as ApiResponse<WorkOrderBatchPreview>;if(!payload.ok)throw new Error(`${payload.error.code} · ${payload.error.message}`);setPreview(payload.data);setSelected(0);}catch(error){setSystemError(error instanceof Error?error.message:'系统读取失败');}finally{setLoading(false);}}
 const rows=preview?.lines??[],active=rows[selected]?.preview,errorCount=preview?.errors.length??0,validCount=rows.filter(item=>item.preview.proposedPreparedRow&&item.preview.errors.length===0).length,fileName=file?.name??'尚未选择工单';const searchLabel=useMemo(()=>preview?`${rows.length} 行 · ${errorCount} 个阻塞`:'等待导入',[preview,rows.length,errorCount]);
 return <div className="operations-console"><aside className="console-rail"><ControlledActionPanel action={action} onActionChange={setAction}/><form onSubmit={submit} className="import-panel"><label>悉尼业务日<input type="date" value={businessDate} onChange={event=>setBusinessDate(event.target.value)} required/></label><input ref={fileInput} className="sr-only" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>setFile(event.target.files?.[0])}/><button className="file-picker" type="button" onClick={()=>fileInput.current?.click()}><FileXls size={21}/><span>{fileName}</span></button><button className="outline-button" disabled={loading||!file} type="submit"><UploadSimple size={18}/>{loading?'解析与读取库存…':'导入 Replacement XLSX'}</button></form><Link className="secondary-workflow" href="/returns"><span><strong>批量退回返修</strong><small>读取 Faulty Unit，默认 REPAIR-01</small></span><ArrowRight size={18}/></Link></aside>
 <section className="console-main"><div className="job-summary"><div><h3>{preview?.sh??'等待导入 RMA 工单'}</h3><p>{fileName}</p></div><span>{preview?'只读预览':'未开始'}</span></div><div className="job-stats"><span>总行数 <b>{rows.length}</b></span><span>有效 <b>{validCount}</b></span><span>警告 <b>{preview?.warnings.length??0}</b></span><span>阻塞 <b>{errorCount}</b></span></div><div className="table-tools"><div><MagnifyingGlass size={17}/>{searchLabel}</div><span>行类型：Replacement</span><span>数据源：实时飞书库存</span></div>{systemError&&<div className="inline-alert danger"><WarningCircle size={19}/>{systemError}</div>}{!preview&&!systemError&&<div className="console-empty"><UploadSimple size={36}/><strong>导入一份 RMA XLSX</strong><span>系统只读取 Replacement Unit information，Faulty Unit 不会混入。</span></div>}{preview&&<div className="console-table-wrap"><table className="console-table"><thead><tr><th>行</th><th>SKU</th><th>机型</th><th>数量</th><th>库存属性</th><th>推荐库位</th><th>可用库存</th><th>状态</th></tr></thead><tbody>{rows.map((item,index)=>{const row=item.preview.proposedPreparedRow,blocked=item.preview.errors.length>0;return <tr className={selected===index?'selected':''} onClick={()=>setSelected(index)} key={`${item.sourceRow??index}-${row?.sku??index}`}><td>{item.sourceRow??'—'}</td><td>{row?.sku??item.preview.extracted.replacementSku??'—'}</td><td>{row?.model??'—'}</td><td>{row?.qty??item.preview.extracted.qty??'—'}</td><td>{row?.stockCondition??'—'}</td><td>{row?.fromLocation??'—'}</td><td>{item.preview.recommendation?.availableQty??'—'}</td><td><span className={`row-status ${blocked?'blocked':'ok'}`}>{blocked?'阻塞':'匹配'}</span></td></tr>;})}</tbody></table></div>}{preview?.warnings.map(warning=><div className="inline-alert warning" key={warning}><WarningCircle size={18}/>{warning}</div>)}</section>
 <aside className="detail-panel"><h3>行详情</h3>{!active?<div className="detail-empty">选择一行查看库存与校验结果。</div>:<><dl><dt>SKU</dt><dd>{active.proposedPreparedRow?.sku??active.extracted.replacementSku??'—'}</dd><dt>机型</dt><dd>{active.proposedPreparedRow?.model??'—'}</dd><dt>数量</dt><dd>{active.proposedPreparedRow?.qty??active.extracted.qty??'—'}</dd><dt>建议来源库位</dt><dd>{active.proposedPreparedRow?.fromLocation??'无可用库位'}</dd></dl><div className="detail-section"><h4>可用库存（替换件）</h4><strong className={active.recommendation?'qty-good':'qty-bad'}>{active.recommendation?.availableQty??0}</strong><p>{active.recommendation?'已找到满足数量的单一库位。':'当前库存无法满足本行需求。'}</p></div>{active.errors.length>0&&<div className="detail-section"><h4>阻塞 / 警告</h4>{active.errors.map(error=><p className="danger-text" key={error.code}>{error.code} · {error.message}</p>)}</div>}</>}<button className="locked-action" disabled><LockSimple size={18}/>确认并写入（UAT 锁定）</button></aside></div>;
}
