import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { evaluateBaselineApproval, parseBaselineReviewCsv } from '../domain/migration/baselineReview.js';
import { createBaselineFreezePreview } from '../domain/migration/freezePreview.js';
import type { BaselineReviewDecisionRecord, MigrationBaselineCandidate } from '../domain/migration/types.js';

// Dry-run only. It reads local review material and produces a local preview; no Feishu or baseline persistence path exists.
const dir=join(process.cwd(),'artifacts'),artifact=JSON.parse(readFileSync(join(dir,'migration-baseline-candidates.json'),'utf8')) as {cutoverAnalysis:{configuredCandidateDate:string};candidates:MigrationBaselineCandidate[]};
const parsed=parseBaselineReviewCsv(readFileSync(join(dir,'migration-baseline-review.csv'),'utf8'),artifact.candidates),bulkPath=join(dir,'migration-baseline-review-decisions.json'),bulk=existsSync(bulkPath)?JSON.parse(readFileSync(bulkPath,'utf8')) as {reviewBatchFingerprint?:string;bulkApprovedDecisions?:BaselineReviewDecisionRecord[];manualDecisions?:BaselineReviewDecisionRecord[]}:undefined,allDecisions=[...parsed.decisions,...(bulk?.bulkApprovedDecisions??[]),...(bulk?.manualDecisions??[])],gate=evaluateBaselineApproval(artifact.candidates,allDecisions,artifact.cutoverAnalysis.configuredCandidateDate,'FULL_BASELINE',parsed.errors),freeze=createBaselineFreezePreview(gate,artifact.cutoverAnalysis.configuredCandidateDate,bulk?.reviewBatchFingerprint?[bulk.reviewBatchFingerprint]:[]);
const preview={mode:'DRY_RUN_ONLY',writesAttempted:0,approvalStatus:freeze?'FROZEN_PREVIEW':gate.approvalStatus,wouldApprove:gate.eligible,parseErrors:parsed.errors,gate:{eligible:gate.eligible,candidateCount:gate.candidateCount,approvedCount:gate.approvedCount,rejectedCount:gate.rejectedCount,deferredCount:gate.deferredCount,pendingDecisionCount:gate.pendingDecisionCount,unresolvedCount:gate.unresolvedCount,readyForApprovalCount:gate.readyForApprovalCount,blockers:gate.blockers},...(freeze?{freeze}:{}),approvedRecords:gate.approvedRecords,rejectedRecords:gate.rejectedRecords,deferredRecords:gate.deferredRecords,pendingRecords:gate.pendingRecords,reviewAudit:gate.reviewAudit};
mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'migration-baseline-approved-preview.json'),JSON.stringify(preview,null,2),'utf8');console.log(JSON.stringify({executed:true,...preview,approvedRecords:undefined,rejectedRecords:undefined,deferredRecords:undefined,pendingRecords:undefined,reviewAudit:undefined},null,2));
