import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createBulkApprovalScope, MigrationApprovalError, prepareBulkApprovalArtifact, previewBulkBaselineApproval } from '../domain/migration/bulkBaselineApproval.js';
import type { BaselineReviewDecisionRecord, LocalReviewDecisionArtifact, MigrationBaselineCandidate } from '../domain/migration/types.js';

// Human-only local artifact command. It never writes Feishu, ledger rows, or a database.
const dir=join(process.cwd(),'artifacts'),candidateArtifact=JSON.parse(readFileSync(join(dir,'migration-baseline-candidates.json'),'utf8')) as {cutoverAnalysis:{configuredCandidateDate:string};candidates:MigrationBaselineCandidate[]},confirm=process.argv.includes('--confirm'),configuredReviewer=process.env.MIGRATION_REVIEWER?.trim(),reviewer=configuredReviewer??'PREVIEW_HUMAN_REQUIRED',reviewedAt=process.env.MIGRATION_REVIEWED_AT?.trim()??new Date().toISOString(),scope=createBulkApprovalScope(candidateArtifact.candidates,candidateArtifact.cutoverAnalysis.configuredCandidateDate);
try {
  if(confirm&&!configuredReviewer)throw new MigrationApprovalError('HUMAN_REVIEWER_REQUIRED');
  const result=previewBulkBaselineApproval({candidates:candidateArtifact.candidates,cutoverDate:candidateArtifact.cutoverAnalysis.configuredCandidateDate,command:{reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer,reviewedAt,decision:'APPROVE_READY_SET',...(process.env.MIGRATION_REVIEW_NOTE?.trim()?{note:process.env.MIGRATION_REVIEW_NOTE.trim()}: {})},principal:{principalType:'HUMAN',principalId:`cli:${reviewer}`,permissions:['MIGRATION_REVIEW','MIGRATION_APPROVE','MIGRATION_FREEZE']},confirm});
  if(confirm){const path=join(dir,'migration-baseline-review-decisions.json'),existing=existsSync(path)?JSON.parse(readFileSync(path,'utf8')) as LocalReviewDecisionArtifact:undefined,next=prepareBulkApprovalArtifact(existing,result);mkdirSync(dir,{recursive:true});writeFileSync(path,JSON.stringify(next,null,2),'utf8');writeFileSync(join(dir,'migration-baseline-review-bulk-filled.csv'),filledCsv(candidateArtifact.candidates,result.bulkApprovedDecisions), 'utf8');}
  console.log(JSON.stringify({executed:true,mode:result.mode,writesAttempted:0,eligibleCandidates:result.scope.candidateCount,wouldApprove:result.wouldApprove,writtenDecisions:result.writtenDecisions,reviewBatchFingerprint:result.scope.reviewBatchFingerprint,bulkApprovalId:result.bulkApprovalId},null,2));
} catch(error) {const code=error instanceof MigrationApprovalError?error.code:error instanceof Error?error.message:'UNKNOWN_ERROR';console.log(JSON.stringify({executed:false,writesAttempted:0,error:code},null,2));process.exitCode=1;}

function filledCsv(candidates:readonly MigrationBaselineCandidate[],decisions:readonly BaselineReviewDecisionRecord[]):string{const byId=new Map(decisions.map(item=>[item.baselineId,item])),header=['Baseline ID','Candidate Fingerprint','SN','SKU','Location','Condition','Reviewer Decision','Reviewer','Reviewed At','Reviewer Note','Decision Source','Bulk Approval ID'],rows=candidates.map(item=>{const decision=byId.get(item.baselineId);return [item.baselineId,item.candidateFingerprint,item.sn,item.sku,item.location,item.stockCondition,decision?.decision??'',decision?.reviewer??'',decision?.reviewedAt??'',decision?.note??'',decision?.source??'',decision?.bulkApprovalId??''];});return [header,...rows].map(row=>row.map(csv).join(',')).join('\r\n');}
function csv(value:string):string{return /[",\r\n]/.test(value)?`"${value.replaceAll('"','""')}"`:value;}
