import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DeterministicBaselineCandidateService } from '../domain/migration/baselineCandidate.js';
import { BaselineReplaySimulation, draftMigrationManifest } from '../domain/migration/baselineReconciliation.js';
import { analyzeCutoverDates, createCutoverPolicy } from '../domain/migration/cutoverPolicy.js';
import { normalizeLocation, normalizeSku, normalizeStockCondition } from '../domain/migration/normalization.js';
import { evaluateBaselineApproval } from '../domain/migration/baselineReview.js';
import type { CurrentInventorySnSource, PhysicalSnSource, ProductMasterSource } from '../domain/migration/types.js';
import { DeterministicMovementProjectionService } from '../domain/movement/movementProjection.js';
import { DefaultMigrationPolicy, FEISHU_OPERATIONAL_SOURCE_BATCHES } from '../domain/movement/migrationPolicy.js';
import { AuditOnlyPositionalReader } from '../feishu/auditOnlyReader.js';
import { requiredEnv } from '../feishu/client.js';
import type { TypedSheetData } from '../feishu/types.js';
import { FeishuWarehouseReadAdapter } from '../feishu/warehouseReadAdapter.js';

// Pure read/project/compare plan generation. It has no Feishu writer or mutation dependency.
const spreadsheetUrl=requiredEnv('FEISHU_SPREADSHEET_URL'),mainSheetId=requiredEnv('FEISHU_MAIN_SHEET_ID'),currentSheetId=requiredEnv('FEISHU_CURRENT_INVENTORY_SHEET_ID'),physicalSheetId=requiredEnv('FEISHU_SERIALIZED_INVENTORY_SHEET_ID'),productSheetId=requiredEnv('FEISHU_PRODUCT_SHEET_ID'),baselineDate=requiredEnv('MIGRATION_BASELINE_DATE');
const reader=new AuditOnlyPositionalReader(spreadsheetUrl,{[mainSheetId]:{lastColumn:'AC',rowCount:Number(process.env.FEISHU_MAIN_ROW_COUNT??2342),numericColumns:['K']},[currentSheetId]:{lastColumn:'T',rowCount:Number(process.env.FEISHU_CURRENT_INVENTORY_ROW_COUNT??1000),numericColumns:['H']},[physicalSheetId]:{lastColumn:'E',rowCount:Number(process.env.FEISHU_SERIALIZED_ROW_COUNT??1000)},[productSheetId]:{lastColumn:'T',rowCount:Number(process.env.FEISHU_PRODUCT_ROW_COUNT??200),numericColumns:['F','G','H']}});
const adapter=new FeishuWarehouseReadAdapter({spreadsheetUrl,mainSheetId,currentInventorySheetId:currentSheetId},reader);
const [ledger,currentInventory,physicalTable,productTable]=await Promise.all([adapter.readLedgerRecords(),adapter.readCurrentInventory(),reader.readTable({sheetId:physicalSheetId,noHeader:true}),reader.readTable({sheetId:productSheetId,noHeader:true})]);
const physical=parsePhysical(physicalTable),explicitCurrent:CurrentInventorySnSource[]=currentInventory.filter((item):item is typeof item&{sn:string}=>Boolean(item.sn)).map(item=>({sn:item.sn,sku:item.sku,location:item.location,stockCondition:item.condition,evidenceScope:'SN_EXACT',...(item.displayName?{displayName:item.displayName}:{})})),currentSerialized=mergeCurrentEvidence(explicitCurrent,allocateAggregateEvidence(currentInventory,physical)),products=parseProducts(productTable);
const candidates=await new DeterministicBaselineCandidateService({baselineDate,physical,currentInventory:currentSerialized,ledger,products}).build();
const movementProjection=new DeterministicMovementProjectionService(new DefaultMigrationPolicy(undefined,FEISHU_OPERATIONAL_SOURCE_BATCHES)).projectLedgerRecords(ledger),policy=createCutoverPolicy(baselineDate),approvalPreview=evaluateBaselineApproval(candidates,[],baselineDate),simulation=new BaselineReplaySimulation().simulate({candidates,approvedPreviewCandidates:[],movements:movementProjection.movements,policy,physicalTarget:physical});
const createdAt=new Date().toISOString(),manifest=draftMigrationManifest({migrationId:`MIG-${baselineDate.replaceAll('-','')}-DRAFT`,cutoverDate:baselineDate,createdAt,physicalCount:physical.length,currentProjectionCount:currentInventory.length,ledgerRecordCount:ledger.length,candidates});
const counts=(key:'confidence'|'candidateStatus'|'physicalEvidenceQuality'|'currentEvidenceScope')=>countBy(candidates,item=>item[key]);
const cutoverCandidates=analyzeCutoverDates({physicalSnapshotDate:baselineDate});
const ledgerDates=ledger.map(item=>item.businessDate).filter(Boolean).sort(),systemNativeDates=ledger.filter(item=>item.origin==='SYSTEM_NATIVE').map(item=>item.businessDate).filter(Boolean).sort();
const artifact={generatedAt:createdAt,mode:'READ_ONLY_PLAN',writesAttempted:0,approvalStatus:'DRAFT',summary:{physicalTotal:physical.length,validPhysicalEvidence:candidates.filter(item=>item.physicalEvidenceQuality==='VALID').length,baselineCandidateTotal:candidates.length,confidence:counts('confidence'),verification:countBy(candidates,item=>item.verificationStatus),reviewResolution:countBy(candidates,item=>item.reviewState.resolution),currentEvidenceScope:counts('currentEvidenceScope'),status:counts('candidateStatus'),warnings:countBy(candidates.flatMap(item=>item.warnings),item=>item),blockingIssues:countBy(candidates.flatMap(item=>item.blockingIssues),item=>item)},gapBreakdown:{missingSku:withIssue('MISSING_SKU'),missingLocation:withIssue('MISSING_LOCATION'),invalidCondition:withIssue('INVALID_CONDITION'),invalidSn:withIssue('MANUAL_REVIEW'),locationConflict:withIssue('LOCATION_CONFLICT'),conditionConflict:withIssue('CONDITION_CONFLICT'),skuConflict:withIssue('SKU_CONFLICT'),duplicateSn:withIssue('DUPLICATE_SN'),noCurrentEvidence:withIssue('NO_CURRENT_EVIDENCE'),legacyOnly:withIssue('LEGACY_ONLY')},evidenceBreakdown:countBy(candidates.flatMap(item=>item.evidence),item=>item.source),sourceSummary:{physicalSn:physical.length,currentProjectionRows:currentInventory.length,explicitCurrentSn:explicitCurrent.length,aggregateSupportedSn:currentSerialized.filter(item=>item.evidenceScope==='AGGREGATE_BUCKET').length,ledgerRecords:ledger.length,productMaster:products.length},cutoverAnalysis:{configuredCandidateDate:baselineDate,ledgerDateRange:{earliest:ledgerDates.at(0),latest:ledgerDates.at(-1)},firstReliableSystemNativeDate:systemNativeDates.at(0),sameDayBoundary:policy.sameDayBoundary,automaticSelection:false},cutoverCandidates,manifest,approvalPreview,simulation,candidates,conflicts:candidates.filter(item=>item.verificationStatus==='CONFLICT'),reviewRequired:candidates.filter(item=>item.verificationStatus==='REVIEW_REQUIRED')};
const artifactDir=join(process.cwd(),'artifacts'),jsonPath=join(artifactDir,'migration-baseline-candidates.json'),csvPath=join(artifactDir,'migration-baseline-review.csv');mkdirSync(artifactDir,{recursive:true});writeFileSync(jsonPath,JSON.stringify(artifact,null,2),'utf8');writeFileSync(csvPath,reviewCsv(candidates),'utf8');
console.log(JSON.stringify({executed:true,mode:'READ_ONLY_PLAN',writesAttempted:0,approvalStatus:'DRAFT',summary:artifact.summary,gapBreakdown:artifact.gapBreakdown,sourceSummary:artifact.sourceSummary,cutoverCandidates,simulation,artifacts:{jsonPath,csvPath}},null,2));

function parsePhysical(table:TypedSheetData):PhysicalSnSource[]{const result:PhysicalSnSource[]=[];for(const [index,row] of table.data.slice(1).entries()){const location=text(row[0]),condition=text(row[1]),raw=text(row[2]),ledgerStatus=text(row[3]);if(!raw)continue;const parts=raw.split('/').map(value=>value.trim()),sn=parts.length>=3?parts.at(-1)!:raw,sku=parts.length>=3?parts[0]!:materialCode(ledgerStatus)?ledgerStatus:'';result.push({sn,...(sku?{sku}:{}),...(location?{location}:{}),...(condition?{stockCondition:condition}:{}),sourceRef:`physical-row:${index+2}`});}return result;}
function parseProducts(table:TypedSheetData):ProductMasterSource[]{return table.data.slice(1).map(row=>({sku:text(row[0]),displayName:text(row[1])})).filter(item=>item.sku).map(item=>({sku:item.sku,...(item.displayName?{displayName:item.displayName}:{})}));}
function allocateAggregateEvidence(inventory:Awaited<ReturnType<typeof adapter.readCurrentInventory>>,items:readonly PhysicalSnSource[]):CurrentInventorySnSource[]{const bucketQty=new Map<string,number>();for(const item of inventory){if(item.sn)continue;const key=bucket(item);bucketQty.set(key,(bucketQty.get(key)??0)+item.availableQty);}const physicalGroups=new Map<string,PhysicalSnSource[]>();for(const item of items){if(!item.sku||!item.location||!item.stockCondition)continue;const key=bucket({sku:item.sku,location:item.location,stockCondition:item.stockCondition});physicalGroups.set(key,[...(physicalGroups.get(key)??[]),item]);}const result:CurrentInventorySnSource[]=[];for(const [key,group] of physicalGroups){if((bucketQty.get(key)??0)<group.length)continue;for(const item of group)result.push({sn:item.sn,sku:item.sku!,location:item.location!,stockCondition:item.stockCondition!,evidenceScope:'AGGREGATE_BUCKET'});}return result;}
function mergeCurrentEvidence(explicit:readonly CurrentInventorySnSource[],aggregate:readonly CurrentInventorySnSource[]):CurrentInventorySnSource[]{const exact=new Set(explicit.map(item=>item.sn.trim().toUpperCase()));return [...explicit,...aggregate.filter(item=>!exact.has(item.sn.trim().toUpperCase()))];}
function bucket(item:{sku:string;location:string;stockCondition?:string;condition?:string}):string{return `${normalizeSku(item.sku)??''}|${normalizeLocation(item.location)??''}|${normalizeStockCondition(item.stockCondition??item.condition)??''}`;}
function text(value:unknown):string{return String(value??'').trim();}function materialCode(value:string):boolean{return /^\d{2}-[A-Z0-9-]+$/i.test(value);}
function countBy<T>(items:readonly T[],key:(item:T)=>string):Record<string,number>{const result:Record<string,number>={};for(const item of items){const value=key(item)||'(blank)';result[value]=(result[value]??0)+1;}return result;}
function withIssue(issue:Parameters<typeof candidates[number]['reviewIssues']['includes']>[0]):number{return candidates.filter(item=>item.reviewIssues.includes(issue)).length;}
function reviewCsv(items:typeof candidates):string{const header=['Baseline ID','Candidate Fingerprint','SN','SKU','Location','Condition','Physical Evidence','Current Projection Evidence','Current Evidence Scope','Ledger Evidence','Confidence','Verification Status','Blocking Issues','Warnings','Review Reason Codes','Reviewer Decision','Override SKU','Override Location','Override Condition','Reviewer','Reviewed At','Reviewer Note'];const rows=items.map(item=>[item.baselineId,item.candidateFingerprint,item.sn,item.sku,item.location,item.stockCondition,evidence(item,'PHYSICAL_SN'),evidence(item,'CURRENT_INVENTORY_PROJECTION'),item.currentEvidenceScope,evidence(item,'OPERATIONAL_LEDGER'),item.confidence,item.verificationStatus,item.blockingIssues.join('|'),item.warnings.join('|'),item.reviewState.reviewReasonCodes.join('|'),'','','','','','','']);return [header,...rows].map(row=>row.map(csv).join(',')).join('\r\n');}
function evidence(item:typeof candidates[number],source:string):string{return item.evidence.filter(value=>value.source===source).map(value=>`${value.field}=${value.value}`).join('; ');}
function csv(value:string):string{return `"${value.replaceAll('"','""')}"`;}
