import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { DeterministicBaselineCandidateService } from '../src/domain/migration/baselineCandidate.js';
import { BaselineReplaySimulation, draftMigrationManifest } from '../src/domain/migration/baselineReconciliation.js';
import { createCutoverPolicy } from '../src/domain/migration/cutoverPolicy.js';
import type { BaselineCandidateInput, MigrationBaselineCandidate, PhysicalSnSource } from '../src/domain/migration/types.js';
import type { InventoryMovement, OperationalLedgerRecord } from '../src/domain/movement/types.js';

const baselineDate='2026-08-25',product={sku:'SKU1',displayName:'Model 1'};
function source(overrides:Partial<PhysicalSnSource>={}):PhysicalSnSource{return {sn:'60HD103064PM133',sku:'SKU1',location:'A',stockCondition:'新机',...overrides};}
function input(overrides:Partial<BaselineCandidateInput>={}):BaselineCandidateInput{return {baselineDate,physical:[source()],currentInventory:[source() as Required<PhysicalSnSource>],ledger:[],products:[product],...overrides};}
async function candidates(overrides:Partial<BaselineCandidateInput>={}):Promise<MigrationBaselineCandidate[]>{return new DeterministicBaselineCandidateService(input(overrides)).build();}

test('candidate from agreeing physical and current projection is high-confidence',async()=>{const [item]=await candidates();assert.equal(item?.confidence,'HIGH');assert.equal(item?.verificationStatus,'VERIFIED');assert.equal(item?.candidateStatus,'READY');assert.equal(item?.baselineId,'BASE-20260825-000001');});
test('physical and current location conflict is never guessed',async()=>{const [item]=await candidates({currentInventory:[{...source(),location:'B'} as Required<PhysicalSnSource>]});assert.equal(item?.verificationStatus,'CONFLICT');assert(item?.reviewIssues.includes('LOCATION_CONFLICT'));assert.equal(item?.location,'A');});
test('condition conflict is explicit',async()=>{const [item]=await candidates({currentInventory:[{...source(),stockCondition:'维修良品'} as Required<PhysicalSnSource>]});assert(item?.reviewIssues.includes('CONDITION_CONFLICT'));assert.equal(item?.verificationStatus,'CONFLICT');});
test('SKU conflict is explicit',async()=>{const [item]=await candidates({currentInventory:[{...source(),sku:'SKU2'} as Required<PhysicalSnSource>]});assert(item?.reviewIssues.includes('SKU_CONFLICT'));assert.equal(item?.sku,'SKU1');});
test('missing SKU requires review and is not approved',async()=>{const [item]=await candidates({physical:[{sn:'60HD103064PM133',location:'A',stockCondition:'新机'}],currentInventory:[],ledger:[],products:[]});assert(item?.reviewIssues.includes('MISSING_SKU'));assert.equal(item?.verificationStatus,'REVIEW_REQUIRED');assert.equal(item?.candidateOnly,true);});
test('duplicate canonical 0/R SN is a conflict',async()=>{const [first,second]=await candidates({physical:[source(),source({sn:'60HD103R64PM133'})]});assert(first?.reviewIssues.includes('DUPLICATE_SN'));assert.equal(first?.canonicalSn,second?.canonicalSn);assert.equal(first?.verificationStatus,'CONFLICT');});

test('baseline replay starts from candidate state',()=>{const report=simulate([readyCandidate()],[],[source()]);assert.equal(report.replayInStock,1);assert.equal(report.matched,1);assert.equal(report.rawMatchRate,1);});
test('pre-cutover history remains visible but cannot alter baseline',()=>{const history=movement('OLD','2026-08-20','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[history],[source()]);assert.equal(report.matched,1);assert.equal(report.historicalEvidenceCount,1);assert.equal(report.replayConflicts,0);});
test('same-day movement remains historical and is reported as ordering risk',()=>{const sameDay=movement('SAME',baselineDate,'出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[sameDay],[source()]);assert.equal(report.matched,1);assert.equal(report.orderingRiskMovementCount,1);assert.equal(report.postCutoverMovements,0);});
test('post-cutover MOVE changes baseline location',()=>{const move=movement('MOVE','2026-08-26','移库','TRANSFER',{workflow:'MOVE',fromLocation:'A',toLocation:'B',stockConditionBefore:'新机',stockConditionAfter:'新机'});const report=simulate([readyCandidate()],[move],[source({location:'B'})]);assert.equal(report.matched,1);assert.equal(report.postCutoverMovements,1);});
test('post-cutover OUTBOUND removes the baseline unit',()=>{const outbound=movement('OUT','2026-08-26','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[outbound],[]);assert.equal(report.replayInStock,0);assert.equal(report.replayConflicts,0);});
test('post-cutover RETURN_REPAIR re-enters pending repair stock',()=>{const outbound=movement('OUT','2026-08-26','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'}),returned=movement('RET','2026-08-27','退回维修','INCREASE',{workflow:'RETURN_REPAIR',toLocation:'REPAIR-01',stockConditionAfter:'待修',shNo:'SH-1'});const report=simulate([readyCandidate()],[outbound,returned],[source({location:'REPAIR-01',stockCondition:'待修'})]);assert.equal(report.matched,1);});
test('post-cutover REPAIR_COMPLETE transitions pending repair to repaired good',()=>{const repair=movement('REPAIR','2026-08-26','库存调增','STATE_TRANSITION',{workflow:'REPAIR_COMPLETE',fromLocation:'REPAIR-01',toLocation:'FLEX-01',stockConditionBefore:'待修',stockConditionAfter:'维修良品'});const report=simulate([readyCandidate({location:'REPAIR-01',stockCondition:'待修'})],[repair],[source({location:'FLEX-01',stockCondition:'维修良品'})]);assert.equal(report.matched,1);assert.equal(report.replayConflicts,0);});
test('migration manifest is draft-only',()=>{const manifest=draftMigrationManifest({migrationId:'MIG-1',cutoverDate:baselineDate,createdAt:'2026-08-25T00:00:00Z',physicalCount:1,currentProjectionCount:1,ledgerRecordCount:1,candidates:[readyCandidate()]});assert.equal(manifest.approvalStatus,'DRAFT');assert.equal(manifest.verifiedCount,1);assert.equal('approvedBy' in manifest,false);});
test('baseline plan generator has no Feishu write or approval path',()=>{const source=readFileSync('src/scripts/generateMigrationBaseline.ts','utf8');for(const forbidden of ['OpenApiLedgerWriter','prepareLedgerWrite','writeExplicitCells','executeControlledLedgerOperation','batchUpdate','APPROVED'])assert.equal(source.includes(forbidden),false);assert(source.includes('writesAttempted:0'));});

function readyCandidate(overrides:Partial<MigrationBaselineCandidate>={}):MigrationBaselineCandidate{return {baselineId:'BASE-20260825-000001',sn:'60HD103064PM133',canonicalSn:'60HD103*64PM133',sku:'SKU1',location:'A',stockCondition:'新机',baselineDate,evidence:[],verificationStatus:'VERIFIED',reviewIssues:[],confidence:'HIGH',candidateStatus:'READY',physicalEvidenceQuality:'VALID',candidateOnly:true,...overrides};}
function simulate(baseline:MigrationBaselineCandidate[],movements:InventoryMovement[],physical:PhysicalSnSource[]){return new BaselineReplaySimulation().simulate({candidates:baseline,movements,policy:createCutoverPolicy(baselineDate),physicalTarget:physical});}
function movement(id:string,date:string,ledgerAction:InventoryMovement['ledgerAction'],inventoryEffect:InventoryMovement['inventoryEffect'],overrides:Partial<InventoryMovement>):InventoryMovement{return {movementId:`LEGACY-${id}`,identityAuthority:'LEGACY',origin:'LEGACY_MIGRATION',replayEligibility:'CURRENT_STATE',sourceSequence:1,sourceRecordRef:{sourceSystem:'FEISHU_LEDGER',sourceType:'OPERATIONAL_LEDGER',internalRecordKey:id},businessDate:date,ledgerAction,sku:'SKU1',sn:'60HD103064PM133',qty:1,inventoryEffect,verificationStatus:'VERIFIED',...overrides};}
