import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { DeterministicBaselineCandidateService } from '../src/domain/migration/baselineCandidate.js';
import { BaselineReplaySimulation, draftMigrationManifest } from '../src/domain/migration/baselineReconciliation.js';
import { createCutoverPolicy } from '../src/domain/migration/cutoverPolicy.js';
import { auditPostCutover } from '../src/domain/migration/postCutoverAudit.js';
import { evaluateBaselineApproval, parseBaselineReviewCsv } from '../src/domain/migration/baselineReview.js';
import { createBulkApprovalScope, MigrationApprovalError, prepareBulkApprovalArtifact, previewBulkBaselineApproval } from '../src/domain/migration/bulkBaselineApproval.js';
import { createBaselineFreezePreview } from '../src/domain/migration/freezePreview.js';
import type { BaselineCandidateInput, MigrationBaselineCandidate, PhysicalSnSource } from '../src/domain/migration/types.js';
import type { InventoryMovement, OperationalLedgerRecord } from '../src/domain/movement/types.js';

const baselineDate='2026-08-25',product={sku:'SKU1',displayName:'Model 1'};
function source(overrides:Partial<PhysicalSnSource>={}):PhysicalSnSource{return {sn:'60HD103064PM133',sku:'SKU1',location:'A',stockCondition:'新机',...overrides};}
function input(overrides:Partial<BaselineCandidateInput>={}):BaselineCandidateInput{return {baselineDate,physical:[source()],currentInventory:[source() as Required<PhysicalSnSource>],ledger:[],products:[product],...overrides};}
async function candidates(overrides:Partial<BaselineCandidateInput>={}):Promise<MigrationBaselineCandidate[]>{return new DeterministicBaselineCandidateService(input(overrides)).build();}

test('physical plus SN-exact current projection is high-confidence',async()=>{const [item]=await candidates();assert.equal(item?.confidence,'HIGH');assert.equal(item?.verificationStatus,'VERIFIED');assert.equal(item?.currentEvidenceScope,'SN_EXACT');assert.equal(item?.candidateStatus,'READY');assert.equal(item?.baselineId,'BASE-20260825-000001');});
test('physical and current location conflict is never guessed',async()=>{const [item]=await candidates({currentInventory:[{...source(),location:'B'} as Required<PhysicalSnSource>]});assert.equal(item?.verificationStatus,'CONFLICT');assert(item?.reviewIssues.includes('LOCATION_CONFLICT'));assert.equal(item?.location,'A');});
test('condition conflict is explicit',async()=>{const [item]=await candidates({currentInventory:[{...source(),stockCondition:'维修良品'} as Required<PhysicalSnSource>]});assert(item?.reviewIssues.includes('CONDITION_CONFLICT'));assert.equal(item?.verificationStatus,'CONFLICT');});
test('SKU conflict is explicit',async()=>{const [item]=await candidates({currentInventory:[{...source(),sku:'SKU2'} as Required<PhysicalSnSource>]});assert(item?.reviewIssues.includes('SKU_CONFLICT'));assert.equal(item?.sku,'SKU1');});
test('historical mismatch is a warning, not a hard current conflict',async()=>{const [item]=await candidates({ledger:[{...ledger('待修'),stockCondition:'待修'}]});assert.equal(item?.verificationStatus,'VERIFIED');assert.equal(item?.confidence,'HIGH');assert.deepEqual(item?.warnings,['HISTORICAL_CONDITION_MISMATCH']);assert.equal(item?.candidateStatus,'READY');});
test('aggregate support is MEDIUM evidence, not SN-exact HIGH evidence',async()=>{const [item]=await candidates({currentInventory:[{...source(),evidenceScope:'AGGREGATE_BUCKET'} as Required<PhysicalSnSource>&{evidenceScope:'AGGREGATE_BUCKET'}]});assert.equal(item?.verificationStatus,'VERIFIED');assert.equal(item?.currentEvidenceScope,'AGGREGATE_BUCKET');assert.equal(item?.confidence,'MEDIUM');});
test('location comparison normalizes case and whitespace',async()=>{const [item]=await candidates({physical:[source({location:' Flex-01 '})],currentInventory:[{...source(),location:'flex-01'} as Required<PhysicalSnSource>]});assert.equal(item?.verificationStatus,'VERIFIED');assert.equal(item?.location,'FLEX-01');assert(!item?.blockingIssues.includes('LOCATION_CONFLICT'));});
test('missing SKU requires review and is not approved',async()=>{const [item]=await candidates({physical:[{sn:'60HD103064PM133',location:'A',stockCondition:'新机'}],currentInventory:[],ledger:[],products:[]});assert(item?.reviewIssues.includes('MISSING_SKU'));assert.equal(item?.verificationStatus,'REVIEW_REQUIRED');assert.equal(item?.candidateOnly,true);});
test('duplicate canonical 0/R SN is a conflict',async()=>{const [first,second]=await candidates({physical:[source(),source({sn:'60HD103R64PM133'})]});assert(first?.reviewIssues.includes('DUPLICATE_SN'));assert.equal(first?.canonicalSn,second?.canonicalSn);assert.equal(first?.verificationStatus,'CONFLICT');});

test('baseline replay starts from candidate state in both modes',()=>{const report=simulate([readyCandidate()],[],[source()]);assert.equal(report.strict.replayInStock,1);assert.equal(report.strict.matched,1);assert.equal(report.strict.rawMatchRate,1);assert.equal(report.permissive.matched,1);assert.equal(report.simulationScope,'BASELINE_ONLY');});
test('strict excludes review-required while permissive includes it',()=>{const report=simulate([readyCandidate({verificationStatus:'REVIEW_REQUIRED',confidence:'LOW',blockingIssues:['MANUAL_REVIEW'],reviewIssues:['MANUAL_REVIEW'],candidateStatus:'MANUAL_REVIEW'})],[],[source()]);assert.equal(report.strict.replayInStock,0);assert.equal(report.permissive.replayInStock,1);});
test('pre-cutover history remains visible but cannot alter baseline',()=>{const history=movement('OLD','2026-08-20','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[history],[source()]);assert.equal(report.strict.matched,1);assert.equal(report.historicalEvidenceCount,1);assert.equal(report.strict.replayConflicts,0);});
test('same-day movement remains historical and is reported as ordering risk',()=>{const sameDay=movement('SAME',baselineDate,'出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[sameDay],[source()]);assert.equal(report.strict.matched,1);assert.equal(report.orderingRiskMovementCount,1);assert.equal(report.postCutoverMovements,0);});
test('post-cutover MOVE changes baseline location',()=>{const move=movement('MOVE','2026-08-26','移库','TRANSFER',{workflow:'MOVE',fromLocation:'A',toLocation:'B',stockConditionBefore:'新机',stockConditionAfter:'新机'});const report=simulate([readyCandidate()],[move],[source({location:'B'})]);assert.equal(report.strict.matched,1);assert.equal(report.postCutoverMovements,1);assert.equal(report.simulationScope,'BASELINE_PLUS_POST_CUTOVER');});
test('post-cutover OUTBOUND removes the baseline unit',()=>{const outbound=movement('OUT','2026-08-26','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'});const report=simulate([readyCandidate()],[outbound],[]);assert.equal(report.strict.replayInStock,0);assert.equal(report.strict.replayConflicts,0);});
test('post-cutover RETURN_REPAIR re-enters pending repair stock',()=>{const outbound=movement('OUT','2026-08-26','出库','DECREASE',{workflow:'OUTBOUND',fromLocation:'A',stockConditionBefore:'新机'}),returned=movement('RET','2026-08-27','退回维修','INCREASE',{workflow:'RETURN_REPAIR',toLocation:'REPAIR-01',stockConditionAfter:'待修',shNo:'SH-1'});const report=simulate([readyCandidate()],[outbound,returned],[source({location:'REPAIR-01',stockCondition:'待修'})]);assert.equal(report.strict.matched,1);});
test('post-cutover REPAIR_COMPLETE transitions pending repair to repaired good',()=>{const repair=movement('REPAIR','2026-08-26','库存调增','STATE_TRANSITION',{workflow:'REPAIR_COMPLETE',fromLocation:'REPAIR-01',toLocation:'FLEX-01',stockConditionBefore:'待修',stockConditionAfter:'维修良品'});const report=simulate([readyCandidate({location:'REPAIR-01',stockCondition:'待修'})],[repair],[source({location:'FLEX-01',stockCondition:'维修良品'})]);assert.equal(report.strict.matched,1);assert.equal(report.strict.replayConflicts,0);});
test('migration manifest is draft-only',()=>{const manifest=draftMigrationManifest({migrationId:'MIG-1',cutoverDate:baselineDate,createdAt:'2026-08-25T00:00:00Z',physicalCount:1,currentProjectionCount:1,ledgerRecordCount:1,candidates:[readyCandidate()]});assert.equal(manifest.approvalStatus,'DRAFT');assert.equal(manifest.verifiedCount,1);assert.equal('approvedBy' in manifest,false);});
test('review APPROVE includes a valid candidate in the gate preview',()=>{const item=readyCandidate();const gate=evaluateBaselineApproval([item],[decision(item,'APPROVE')],baselineDate);assert.equal(gate.eligible,true);assert.equal(gate.approvedCount,1);});
test('VERIFIED candidate without explicit decision remains pending and is never implicitly approved',()=>{const item=readyCandidate(),gate=evaluateBaselineApproval([item],[],baselineDate);assert.equal(gate.approvedCount,0);assert.equal(gate.pendingDecisionCount,1);assert.equal(gate.eligible,false);assert.equal(gate.approvalStatus,'PENDING_HUMAN_REVIEW');});
test('review APPROVE rejects candidate with missing required field',()=>{const item=readyCandidate({sku:'',verificationStatus:'REVIEW_REQUIRED',blockingIssues:['MISSING_SKU'],reviewIssues:['MISSING_SKU']});const gate=evaluateBaselineApproval([item],[decision(item,'APPROVE')],baselineDate);assert.equal(gate.eligible,false);assert(gate.blockers.includes(`INVALID_REVIEW_DECISION:${item.baselineId}`));});
test('valid override is accepted and invalid condition is rejected during CSV import',()=>{const item=readyCandidate({verificationStatus:'REVIEW_REQUIRED',blockingIssues:['MANUAL_REVIEW'],reviewIssues:['MANUAL_REVIEW']});const header='Baseline ID,Candidate Fingerprint,Reviewer Decision,Override SKU,Override Location,Override Condition,Reviewer,Reviewed At,Reviewer Note';const valid=`${header}\n${item.baselineId},${item.candidateFingerprint},OVERRIDE,SKU2,FLEX-01,维修良品,Reviewer,2026-08-25T00:00:00Z,ok`;const parsed=parseBaselineReviewCsv(valid,[item]);assert.equal(parsed.errors.length,0);assert.equal(evaluateBaselineApproval([item],parsed.decisions,baselineDate).approvedCount,1);const invalid=valid.replace('维修良品','good');assert(parseBaselineReviewCsv(invalid,[item]).errors.includes(`INVALID_REVIEW_DECISION:${item.baselineId}`));});
test('stale fingerprint and duplicate decision fail closed',()=>{const item=readyCandidate(),header='Baseline ID,Candidate Fingerprint,Reviewer Decision,Reviewer,Reviewed At';const stale=`${header}\n${item.baselineId},stale,APPROVE,A,2026-08-25`;assert(parseBaselineReviewCsv(stale,[item]).errors.includes(`STALE_REVIEW_DECISION:${item.baselineId}`));const duplicate=`${header}\n${item.baselineId},${item.candidateFingerprint},APPROVE,A,2026-08-25\n${item.baselineId},${item.candidateFingerprint},DEFER,A,2026-08-25`;assert(parseBaselineReviewCsv(duplicate,[item]).errors.includes(`DUPLICATE_REVIEW_DECISION:${item.baselineId}`));});
test('reject and defer review candidates never enter approved preview',()=>{const first=readyCandidate({verificationStatus:'REVIEW_REQUIRED',blockingIssues:['MANUAL_REVIEW'],reviewIssues:['MANUAL_REVIEW']}),second=readyCandidate({baselineId:'BASE-20260825-000002',canonicalSn:'60HD992*64PM133',sn:'60HD992064PM133',candidateFingerprint:'second',verificationStatus:'REVIEW_REQUIRED',blockingIssues:['MANUAL_REVIEW'],reviewIssues:['MANUAL_REVIEW']}),gate=evaluateBaselineApproval([first,second],[decision(first,'REJECT'),decision(second,'DEFER')],baselineDate);assert.equal(gate.approvedCount,0);assert.equal(gate.rejectedCount,1);assert.equal(gate.deferredCount,1);});
test('bulk approval preview expands only READY candidates into explicit audit decisions',()=>{const ready=bulkCandidates(338,0),review=bulkCandidates(0,88,338),all=[...ready,...review],scope=createBulkApprovalScope(all,baselineDate),result=previewBulkBaselineApproval({candidates:all,cutoverDate:baselineDate,command:{reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer:'Human',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'},principal:humanPrincipal(),confirm:false});assert.equal(scope.candidateCount,338);assert.equal(result.wouldApprove,338);assert.equal(result.writtenDecisions,0);assert.equal(result.bulkApprovedDecisions.length,338);assert(result.bulkApprovedDecisions.every(item=>item.decision==='APPROVE'&&item.source==='BULK_APPROVAL'&&item.bulkApprovalId===result.bulkApprovalId));assert(!result.bulkApprovedDecisions.some(item=>review.some(candidate=>candidate.baselineId===item.baselineId)));});
test('confirmed bulk approval remains local and full baseline retains 88 pending',()=>{const ready=bulkCandidates(338,0),review=bulkCandidates(0,88,338),all=[...ready,...review],scope=createBulkApprovalScope(all,baselineDate),result=previewBulkBaselineApproval({candidates:all,cutoverDate:baselineDate,command:{reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer:'Human',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'},principal:humanPrincipal(),confirm:true}),gate=evaluateBaselineApproval(all,result.bulkApprovedDecisions,baselineDate);assert.equal(result.writtenDecisions,338);assert.equal(gate.approvedCount,338);assert.equal(gate.pendingDecisionCount,88);assert.equal(gate.eligible,false);});
test('bulk approval fails closed for stale batches, AI principals, and duplicate manual decisions',()=>{const item=readyCandidate(),scope=createBulkApprovalScope([item],baselineDate),command={reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer:'Human',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'} as const;assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command:{...command,reviewBatchFingerprint:'stale'},principal:humanPrincipal(),confirm:false}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='STALE_REVIEW_BATCH');assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command,principal:{principalType:'AI',principalId:'copilot',permissions:['MIGRATION_APPROVE']},confirm:false}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='FORBIDDEN');const bulk=previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command,principal:humanPrincipal(),confirm:true}),gate=evaluateBaselineApproval([item],[...bulk.bulkApprovedDecisions,{...decision(item,'APPROVE'),source:'MANUAL_CSV'}],baselineDate);assert(gate.blockers.includes(`DUPLICATE_REVIEW_DECISION:${item.baselineId}`));});
test('confirm requires a real reviewer bound to the human principal',()=>{const item=readyCandidate(),scope=createBulkApprovalScope([item],baselineDate),command={reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer:'PREVIEW_HUMAN_REQUIRED',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'} as const;const preview=previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command,principal:humanPrincipal('PREVIEW_HUMAN_REQUIRED'),confirm:false});assert.equal(preview.writtenDecisions,0);assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command,principal:humanPrincipal('PREVIEW_HUMAN_REQUIRED'),confirm:true}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='HUMAN_REVIEWER_REQUIRED');assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command:{...command,reviewer:'   '},principal:humanPrincipal(''),confirm:true}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='HUMAN_REVIEWER_REQUIRED');assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command:{...command,reviewer:'Douglas'},principal:humanPrincipal('SomeoneElse'),confirm:true}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='REVIEWER_PRINCIPAL_MISMATCH');assert.throws(()=>previewBulkBaselineApproval({candidates:[item],cutoverDate:baselineDate,command:{...command,reviewer:'Douglas'},principal:{principalType:'SERVICE',principalId:'cli:Douglas',permissions:['MIGRATION_APPROVE']},confirm:true}),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='FORBIDDEN');});
test('review batch binds baseline ID to fingerprint and bulk decision IDs are deterministic',()=>{const first=readyCandidate(),second=readyCandidate({baselineId:'BASE-20260825-000002',canonicalSn:'60HD992*64PM133',sn:'60HD992064PM133',candidateFingerprint:'second'}),scopeA=createBulkApprovalScope([first,second],baselineDate),scopeB=createBulkApprovalScope([second,first],baselineDate),scopeChanged=createBulkApprovalScope([first,{...second,candidateFingerprint:'changed'}],baselineDate),scopeSwapped=createBulkApprovalScope([{...first,candidateFingerprint:'second'},{...second,candidateFingerprint:'fingerprint'}],baselineDate);assert.equal(scopeA.reviewBatchFingerprint,scopeB.reviewBatchFingerprint);assert.notEqual(scopeA.reviewBatchFingerprint,scopeChanged.reviewBatchFingerprint);assert.notEqual(scopeA.reviewBatchFingerprint,scopeSwapped.reviewBatchFingerprint);const command={reviewBatchFingerprint:scopeA.reviewBatchFingerprint,reviewer:'Human',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'} as const,bulkA=previewBulkBaselineApproval({candidates:[first,second],cutoverDate:baselineDate,command,principal:humanPrincipal(),confirm:true}),bulkB=previewBulkBaselineApproval({candidates:[second,first],cutoverDate:baselineDate,command,principal:humanPrincipal(),confirm:true});assert.equal(bulkA.bulkApprovalId,bulkB.bulkApprovalId);assert.deepEqual(bulkA.bulkApprovedDecisions.map(item=>item.decisionId),bulkB.bulkApprovedDecisions.map(item=>item.decisionId));});
test('duplicate artifact batch and any overlap fail before a next artifact is prepared',()=>{const candidates=[readyCandidate({baselineId:'BASE-20260825-000001'}),readyCandidate({baselineId:'BASE-20260825-000002',candidateFingerprint:'second',canonicalSn:'60HD992*64PM133',sn:'60HD992064PM133'})],scope=createBulkApprovalScope(candidates,baselineDate),result=previewBulkBaselineApproval({candidates,cutoverDate:baselineDate,command:{reviewBatchFingerprint:scope.reviewBatchFingerprint,reviewer:'Human',reviewedAt:'2026-08-25T00:00:00Z',decision:'APPROVE_READY_SET'},principal:humanPrincipal(),confirm:true}),existing={reviewBatchFingerprint:'older-batch',bulkApprovedDecisions:[result.bulkApprovedDecisions[1]!],manualDecisions:[]},before=JSON.stringify(existing);assert.throws(()=>prepareBulkApprovalArtifact(existing,result),(error:unknown)=>error instanceof MigrationApprovalError&&error.code===`DUPLICATE_REVIEW_DECISION:${candidates[1]!.baselineId}`);assert.equal(JSON.stringify(existing),before);assert.throws(()=>prepareBulkApprovalArtifact({...existing,reviewBatchFingerprint:scope.reviewBatchFingerprint},result),(error:unknown)=>error instanceof MigrationApprovalError&&error.code==='DUPLICATE_REVIEW_BATCH');});
test('freeze fingerprint remains deterministic and decision-sensitive',()=>{const first=readyCandidate(),second=readyCandidate({baselineId:'BASE-20260825-000002',canonicalSn:'60HD992*64PM133',sn:'60HD992064PM133',candidateFingerprint:'second'}),scope=createBulkApprovalScope([first,second],baselineDate),gate=evaluateBaselineApproval([first,second],[{...decision(first,'APPROVE'),decisionId:'d1'},{...decision(second,'REJECT'),decisionId:'d2'}],baselineDate),freezeA=createBaselineFreezePreview(gate,baselineDate,[scope.reviewBatchFingerprint]),freezeB=createBaselineFreezePreview(gate,baselineDate,[scope.reviewBatchFingerprint]),changedGate=evaluateBaselineApproval([first,second],[{...decision(first,'APPROVE'),decisionId:'d1'},{...decision(second,'APPROVE'),decisionId:'d3'}],baselineDate),freezeChanged=createBaselineFreezePreview(changedGate,baselineDate,[scope.reviewBatchFingerprint]);assert(freezeA&&freezeB&&freezeChanged);assert.equal(freezeA.baselineFreezeFingerprint,freezeB.baselineFreezeFingerprint);assert.notEqual(freezeA.baselineFreezeFingerprint,freezeChanged.baselineFreezeFingerprint);});
test('post-cutover audit is not ready without real movements',()=>{const audit=auditPostCutover([],baselineDate);assert.equal(audit.status,'POST_CUTOVER_AUDIT_NOT_READY');assert.equal(audit.reason,'NO_POST_CUTOVER_MOVEMENTS');});
test('baseline plan generator has no Feishu write or approval path',()=>{const source=readFileSync('src/scripts/generateMigrationBaseline.ts','utf8');for(const forbidden of ['OpenApiLedgerWriter','prepareLedgerWrite','writeExplicitCells','executeControlledLedgerOperation','batchUpdate','APPROVED'])assert.equal(source.includes(forbidden),false);assert(source.includes('writesAttempted:0'));});

function readyCandidate(overrides:Partial<MigrationBaselineCandidate>={}):MigrationBaselineCandidate{return {baselineId:'BASE-20260825-000001',sn:'60HD103064PM133',canonicalSn:'60HD103*64PM133',sku:'SKU1',location:'A',stockCondition:'新机',baselineDate,evidence:[],verificationStatus:'VERIFIED',reviewIssues:[],blockingIssues:[],warnings:[],confidence:'HIGH',candidateStatus:'READY',physicalEvidenceQuality:'VALID',currentEvidenceScope:'SN_EXACT',candidateFingerprint:'fingerprint',reviewState:{resolution:'READY_FOR_APPROVAL',resolvedFields:{},unresolvedFields:[],reviewReasonCodes:[]},candidateOnly:true,...overrides};}
function decision(item:MigrationBaselineCandidate,decision:'APPROVE'|'REJECT'|'DEFER'){return {baselineId:item.baselineId,candidateFingerprint:item.candidateFingerprint,decision,reviewer:'Reviewer',reviewedAt:'2026-08-25T00:00:00Z'} as const;}
function humanPrincipal(reviewer='Human'){return {principalType:'HUMAN' as const,principalId:`cli:${reviewer}`,permissions:['MIGRATION_REVIEW','MIGRATION_APPROVE','MIGRATION_FREEZE'] as const};}
function bulkCandidates(readyCount:number,reviewCount:number,start=0):MigrationBaselineCandidate[]{const ready=Array.from({length:readyCount},(_,index)=>bulkCandidate(start+index,'READY_FOR_APPROVAL')),review=Array.from({length:reviewCount},(_,index)=>bulkCandidate(start+readyCount+index,'REVIEW_REQUIRED'));return [...ready,...review];}
function bulkCandidate(index:number,resolution:'READY_FOR_APPROVAL'|'REVIEW_REQUIRED'):MigrationBaselineCandidate{const number=String(index+1).padStart(6,'0');return readyCandidate({baselineId:`BASE-20260825-${number}`,sn:`60HD1030${String(index).padStart(7,'0')}`,canonicalSn:`60HD103*${String(index).padStart(7,'0')}`,candidateFingerprint:`fingerprint-${number}`,verificationStatus:resolution==='READY_FOR_APPROVAL'?'VERIFIED':'REVIEW_REQUIRED',reviewState:{resolution,resolvedFields:{},unresolvedFields:resolution==='READY_FOR_APPROVAL'?[]:['sku'],reviewReasonCodes:[]},blockingIssues:resolution==='READY_FOR_APPROVAL'?[]:['MANUAL_REVIEW'],reviewIssues:resolution==='READY_FOR_APPROVAL'?[]:['MANUAL_REVIEW'],candidateStatus:resolution==='READY_FOR_APPROVAL'?'READY':'MANUAL_REVIEW'});}
function ledger(condition:'待修'|'新机'){return {sourceRecordRef:{sourceSystem:'FEISHU_LEDGER' as const,sourceType:'OPERATIONAL_LEDGER' as const,internalRecordKey:'legacy-test'},businessDate:'2026-08-20',sourceSequence:1,action:'移库' as const,sku:'SKU1',toLocation:'A',stockCondition:condition,sn:'60HD103064PM133',origin:'LEGACY_MIGRATION' as const};}
function simulate(baseline:MigrationBaselineCandidate[],movements:InventoryMovement[],physical:PhysicalSnSource[]){return new BaselineReplaySimulation().simulate({candidates:baseline,movements,policy:createCutoverPolicy(baselineDate),physicalTarget:physical});}
function movement(id:string,date:string,ledgerAction:InventoryMovement['ledgerAction'],inventoryEffect:InventoryMovement['inventoryEffect'],overrides:Partial<InventoryMovement>):InventoryMovement{return {movementId:`LEGACY-${id}`,identityAuthority:'LEGACY',origin:'LEGACY_MIGRATION',replayEligibility:'CURRENT_STATE',sourceSequence:1,sourceRecordRef:{sourceSystem:'FEISHU_LEDGER',sourceType:'OPERATIONAL_LEDGER',internalRecordKey:id},businessDate:date,ledgerAction,sku:'SKU1',sn:'60HD103064PM133',qty:1,inventoryEffect,verificationStatus:'VERIFIED',...overrides};}
