'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, CheckCircle, MapPin, WarningCircle } from '@phosphor-icons/react';
import type { ApiResponse } from '../../../src/application/apiResponse';
import type { ControlledBatchInboundInput, ControlledBatchInboundLine, ControlledBatchInboundPreview } from '../../../src/application/controlledLedgerOperation';
import { STOCK_CONDITIONS } from '../../../src/config/controlledValues';
import { WarehouseMatrix, type MatrixLocation } from '../warehouse-layout/warehouse-matrix';

export function BatchInboundWorkspace({ businessDate, locations }: { businessDate: string; locations: MatrixLocation[] }) {
  const [date,setDate]=useState(businessDate),[text,setText]=useState(''),[sku,setSku]=useState(''),[condition,setCondition]=useState<ControlledBatchInboundLine['stockCondition']>('新机'),[location,setLocation]=useState(''),[container,setContainer]=useState(''),[remark,setRemark]=useState(''),[mapOpen,setMapOpen]=useState(false),[preview,setPreview]=useState<ControlledBatchInboundPreview>(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const lines=useMemo(()=>parseInbound(text,{sku,toLocation:location,stockCondition:condition,containerCode:container,remark}),[text,sku,location,condition,container,remark]);
  async function request(path:string, body:object) { const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const result=await response.json() as ApiResponse<ControlledBatchInboundPreview & {rows?:number[];status?:string}>; if(!result.ok) throw new Error(`${result.error.code} · ${result.error.message}`); return result.data; }
  async function createPreview(){ if(!lines.length)return; setBusy(true);setMessage('');setPreview(undefined);try{setPreview(await request('/api/warehouse/operations/inbound/preview',{date,lines}));}catch(error){setMessage(error instanceof Error?error.message:'批量入库预览失败');}finally{setBusy(false);} }
  async function confirm(){ if(!preview||preview.blockedCount)return; setBusy(true);setMessage('');try{const result=await request('/api/warehouse/operations/inbound/execute',{date,lines,commandId:preview.commandId} satisfies ControlledBatchInboundInput);setMessage(result.status==='ALREADY_COMMITTED'?'该批次此前已完成，未重复写入。':`已写入并复核 ${result.rows?.length??0} 条入库流水。`);}catch(error){setMessage(error instanceof Error?error.message:'批量入库失败');}finally{setBusy(false);} }
  const success=message.includes('已写入')||message.includes('此前');
  return <section className="batch-transfer batch-inbound">
    <header className="batch-transfer-header"><div><span className="workflow-kicker">BATCH INBOUND</span><h3>批量入库</h3><p>支持扫描清单或 Excel/飞书表格粘贴；预览逐台校验，默认全有或全无。</p></div></header>
    <div className="batch-transfer-grid">
      <div className="batch-input-card"><div className="batch-card-title"><span>01</span><div><h4>粘贴 SN 或明细</h4><p>单列 SN，或 SN / SKU / 库位 / 库存属性 / 容器 / 备注（Tab 分隔）。</p></div></div><label>业务日期<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPreview(undefined);}}/></label><label>批量 SN / 明细<textarea value={text} onChange={e=>{setText(e.target.value);setPreview(undefined);}} placeholder={'60HD103064PM133\n60KB103061NB141\n或：SN\tSKU\tR1-1-1-L\t新机\tBOX-1'} /></label><div className="batch-count"><strong>{lines.length}</strong><span>行待校验</span></div></div>
      <div className="batch-target-card"><div className="batch-card-title"><span>02</span><div><h4>默认入库资料</h4><p>单列 SN 时应用；明细行内填写的值优先。</p></div></div><label>料号<input value={sku} onChange={e=>{setSku(e.target.value);setPreview(undefined);}} placeholder="SKU"/></label><label>库存属性<select value={condition} onChange={e=>{setCondition(e.target.value as ControlledBatchInboundLine['stockCondition']);setPreview(undefined);}}>{STOCK_CONDITIONS.map(item=><option key={item}>{item}</option>)}</select></label><button type="button" className={`visual-location-trigger${location?' selected':''}`} onClick={()=>setMapOpen(true)}><MapPin size={22}/><span><small>目标库位</small><strong>{location||'从仓库图选择'}</strong></span><ArrowRight size={17}/></button><label>容器（可选）<input value={container} onChange={e=>setContainer(e.target.value)}/></label><label>备注（可选）<input value={remark} onChange={e=>setRemark(e.target.value)}/></label></div>
    </div>
    <div className="batch-preview-card"><div className="batch-card-title"><span>03</span><div><h4>批次预览</h4><p>READY 才可确认；任何 BLOCKED 行都会阻止整批写入。</p></div></div>
      {preview&&<><div className="batch-preview-summary"><strong>{preview.readyCount} READY</strong><span>{preview.blockedCount} BLOCKED</span><span>{preview.totalRows} 条流水</span><small>{preview.commandId}</small></div><div className="batch-preview-table-wrap"><table className="batch-preview-table"><thead><tr><th>SN</th><th>SKU</th><th>库位</th><th>属性</th><th>状态</th></tr></thead><tbody>{preview.lines.map((item,index)=><tr key={`${item.line.sn}-${index}`}><td>{item.line.sn}</td><td>{item.line.sku}</td><td>{item.line.toLocation}</td><td>{item.line.stockCondition}</td><td><span className={`row-status ${item.status==='READY'?'ok':'blocked'}`}>{item.status==='READY'?'READY':item.reason}</span></td></tr>)}</tbody></table></div>{preview.warnings.map(w=><div className="inline-alert warning" key={w}><WarningCircle size={17}/>{w}</div>)}</>}
      {message&&<div className={`inline-alert ${success?'success':'danger'}`}><CheckCircle size={17}/>{message}</div>}
      <div className="batch-action-bar">{!preview?<button className="execute-button" type="button" disabled={busy||!lines.length} onClick={createPreview}>{busy?'逐台校验中…':'生成批量入库预览'}<ArrowRight size={18}/></button>:<button className="confirm-write-button" type="button" disabled={busy||preview.blockedCount>0} onClick={confirm}>{busy?'写入并复核中…':preview.blockedCount>0?'删除或修正 BLOCKED 行后重新预览':`确认 ${preview.readyCount} 台入库`}</button>}</div>
    </div>
    {mapOpen&&<div className="map-modal" role="dialog" aria-modal="true"><div className="map-modal-card"><header><div><h3>选择入库目标库位</h3></div><button onClick={()=>setMapOpen(false)}>关闭</button></header><WarehouseMatrix locations={locations} selectionMode="target" selectedLocation={location} onSelect={value=>{setLocation(value);setMapOpen(false);setPreview(undefined);}}/></div></div>}
  </section>;
}

function parseInbound(value:string,defaults:Omit<ControlledBatchInboundLine,'sn'>):ControlledBatchInboundLine[]{return value.split(/\r?\n/).map(raw=>raw.trim()).filter(Boolean).map(raw=>{const cells=raw.split('\t').map(item=>item.trim());return{sn:cells[0]??'',sku:cells[1]||defaults.sku,toLocation:cells[2]||defaults.toLocation,stockCondition:(cells[3]||defaults.stockCondition) as ControlledBatchInboundLine['stockCondition'],...(cells[4]||defaults.containerCode?{containerCode:cells[4]||defaults.containerCode}:{}),...(cells[5]||defaults.remark?{remark:cells[5]||defaults.remark}:{})};});}
